# Generated by Django 4.2 on 2026-02-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='message',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user_feedback',
        ),
    ]
